name: "New release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "GitFlow: Create release branch"
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Add Github Package Registry Auth Token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GPR_ACCESS_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Prepare release
        run: yarn run release-it --ci --increment ${{ github.event.inputs.version }}
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: Release version ${{ github.event.inputs.version }}
#          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.

            I've updated the changelog, bumped the versions in the manifest files and created a draft release.
            Merging this PR will publish the release and deploy it to production!
        env:
          # DEPLOY_TOKEN: We have to use a personal access token to trigger a new workflow, see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
