name: CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  pull_request:
  schedule:
    - cron:  '0 4 * * 1' # Mondays at 4am

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Add Github Package Registry Auth Token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GPR_ACCESS_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
        env:
          CI: true
